### ISSUE TITLE
`npm i inference-engine-node` meets error for version 0.1.5

### ISSUE THREAD

**Issue by lionkunonly** [intel/inference-engine-node#49]
I try install the inference-engine-node v0.1.5 in other projects. But the `npm` reports an error:
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/inference-engine-node/example/hello_classification_node" as it does not contain a package.json file.
```
It is a strange error, because there is a `package.js` in the `hello_classification_node`. I do not know why this error happen. Could you help solve it? @huningxin

**Comment by huningxin** [comment]
Thanks for reporting this issue @lionkunonly ! I can reproduce on my side. 

I am wondering whether it is caused by this line at package.json https://github.com/intel/inference-engine-node/blob/master/package.json#L27. It was introduced by https://github.com/intel/inference-engine-node/commit/bd36eb49d6c7c3c5ea3d6cbfb898060a88acf0be. @artyomtugaryov , as you wrote that commit, do you have any thoughts?

**Comment by huningxin** [comment]
inference-engine-node 0.1.6 with this fix is published at https://www.npmjs.com/package/inference-engine-node
